### ISSUE TITLE
Seth Desktop 的 GTK+ 前端会在 frontends.gtk.auto.dialup=1 时启动时断开连接，这是 bug 还是 feature？

### ISSUE THREAD

**Issue by nswa-project** [seth-project/sdk#1]
相关代码：

https://github.com/seth-project/sdk/blob/master/desktop/frontend-gtk.cc#L344-L346

复现方法：启动 GTK+ 前端，设置 `frontends.gtk.auto.dialup=1` 高级选项，连接，关闭程序，在连接的情况下重新打开 GTK+ 前端，连接挂断。

我看配置文件里还有一个 `frontends.gtk.auto.hangup` 显示 `not impl yet`。所以这是一个 BUG?

**Comment by seth-nk** [comment]
是的，这是一个 Bug，修复程序将会稍后发布。

**Comment by seth-nk** [comment]
fixed
